### PR TITLE
Simple landing page

### PR DESCRIPTION
**Pull request by kennethd24**
- Added landing page after login
- Added hamburger menu
- Added back functionality on navbar

### CODE REVIEW

**Comment by Lordnickim** [comment]
Looks good thou do we still need the commented out parts in shared.tsx? @kennethd24

**Comment by kennethd24** [comment]
I left them, because I couldn't get the css to be perfectly centered and just wanted reference for work down the line

**Comment by Lordnickim** [comment]
Looks good to me wanna 'Request' anyone else to look at it?
@kennethd24

**Review by austinchadoyeon — COMMENTED** [review]
Looks good to me. Will need to pull this down and resolve any conflicts on my end

**Pull request merged**
